name: Mise à jour stats football

on:
  schedule:
    - cron: '30 15 * * *'  # 15h30 UTC = 17h30 heure française (été)
    - cron: '30 17 * * *'  # 17h30 UTC = 19h30 heure française (été)
    - cron: '50 21 * * *'  # 21h50 UTC = 23h50 heure française (été)
  workflow_dispatch:

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Lancer le script
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
        run: node fetch-stats.js

      - name: Sauvegarder les fichiers
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json photos.json
          git diff --staged --quiet || git commit -m "Stats du $(date '+%d/%m/%Y a %Hh%M')"
          git push
